version: "3.7"

services:
    rabbitmq:
        image: rabbitmq:3.10-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"

    discovery-service:
        image: discovery-service:latest
        container_name: discovery-service
        depends_on:
            - mongo
        ports:
            - "8761:8761"
        #environment:
        #    - eureka.client.register-with-eureka=false
        #    - eureka.client.fetch-registry=false

    config-service:
        image: config-service:latest
        container_name: config-service
        ports:
            - "8888:8888"
        #environment:
        #    - spring.cloud.config.server.git.uri=https://github.com/gianca1994/springboot-microservices-config
        #    - spring.cloud.config.server.git.clone-on-start=true

    car-service:
        image: car-service:latest
        container_name: car-service
        depends_on:
            - config-service
            - discovery-service
            - rabbitmq
            - mongo
        #environment:
        #    - spring.cloud.config.uri=http://config-service:8888
        #    - management.endpoints.web.exposure.include=*
        #    - spring.cloud.config.profile=dev

    mongo:
        image: mongo:latest
        container_name: mongo
        volumes:
            - ./data/db:/data/db