version: "3.7"

services:
    rabbitmq:
        image: rabbitmq:3.10-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - red

    discovery-service:
        image: discovery-service:latest
        container_name: discovery-service
        ports:
            - "8761:8761"
        networks:
            - red

    config-service:
        image: config-service:latest
        container_name: config-service
        ports:
            - "8888:8888"
        networks:
            - red

    mongo:
        image: mongo:latest
        container_name: mongo
        volumes:
            - ./data/db:/data/db
        networks:
            - red

    car-service:
        image: car-service:latest
        container_name: car-service
        depends_on:
            - config-service
            - discovery-service
            - rabbitmq
            - mongo
        environment:
            - 'spring.rabbitmq.host=${RABBITMQ_HOST}'
            - 'spring.rabbitmq.port=${RABBITMQ_PORT}'
            - 'spring.rabbitmq.username=${RABBITMQ_USERNAME}'
            - 'spring.rabbitmq.password=${RABBITMQ_PASSWORD}'

            - 'eureka.client.serviceUrl.defaultZone=${EUREKA_URL}'
            - 'eureka.instance.preferIpAddress=${EUREKA_PREFER_IP_ADDRESS}'

            - 'spring.cloud.config.uri=${CONFIG_URL}'
            - 'spring.cloud.config.fail-fast=${CONFIG_FAIL_FAST}'
            - 'spring.cloud.config.retry.maxAttempts=${CONFIG_RETRY_MAX_ATTEMPTS}'
            - 'management.endpoints.web.exposure.include=${CONFIG_EXPOSURE_INCLUDE}'
            - 'spring.cloud.config.profile=${CONFIG_PROFILE}'
        networks:
            - red

networks:
    red: